import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { matchCasing, resolveForm } from './utils.js';

/**
 * ============================================================================
 * PART 1: PURE TRANSLATION UTILITIES
 * ============================================================================
 */

/**
 * Evaluates the spaCy UPOS (Universal Part of Speech) tag to extract the correct 
 * translation from a specific dictionary entry.
 * @param {string} pos - The coarse POS tag from spaCy (e.g., 'VERB', 'NOUN')
 * @param {object} brainEntry - The specific dictionary definition object for the target word.
 * @returns {string|null} The raw, unconjugated Inglisce replacement word.
 */
export const getReplacement = (pos, brainEntry) => {
    // Verbs and Auxiliaries share verb roots in the dictionary.
    if ((pos === 'VERB' || pos === 'AUX') && brainEntry.Verb) return brainEntry.Verb;

    // Fallbacks for Auxiliaries: If spaCy flags a word as a helper (like 'have' or 'be'),
    // we explicitly check if the dictionary provides a unique Copula or Modal translation.
    if (pos === 'AUX') {
        if (brainEntry.Copula) return brainEntry.Copula;
        if (brainEntry.Auxiliary) return brainEntry.Auxiliary;
        if (brainEntry.Modal) return brainEntry.Modal;
    }

    // Standard part-of-speech routing
    if ((pos === 'NOUN' || pos === 'PROPN') && brainEntry.Noun) return brainEntry.Noun;
    if (pos === 'ADJ' && brainEntry.Adjective) return brainEntry.Adjective;
    if (pos === 'ADV' && brainEntry.Adverb) return brainEntry.Adverb;
    if (pos === 'PRON' && brainEntry.Pronoun) return brainEntry.Pronoun;
    if (pos === 'DET' && brainEntry.Determiner) return brainEntry.Determiner;

    // Prepositions and Conjunctions often share functional space
    if ((pos === 'ADP' || pos === 'SCONJ' || pos === 'CCONJ')) {
        if (brainEntry.Preposition) return brainEntry.Preposition;
        if (brainEntry.Conjunction) return brainEntry.Conjunction;
    }

    // Absolute Fallback (The Option Pattern context): 
    // If the word exists in the dictionary, but spaCy's POS tag doesn't perfectly match 
    // our strict keys above, we just safely grab whatever the first available translation is.
    const keys = Object.keys(brainEntry).filter(k => k !== 'conjugations');
    return keys.length > 0 ? brainEntry[keys[0]] : null;
};

/**
 * Conjugates the base Inglisce word based on spaCy's fine-grained Penn Treebank tags.
 * Evaluates custom conjugations from the dictionary before falling back to standard suffix math.
 * @param {object} brainEntry - The full dictionary entry, containing potential irregular conjugations.
 * @param {string} word - The base translation (e.g., 'sitt')
 * @param {string} tag - The fine-grained POS tag (e.g., 'VBG' for Gerund)
 * @returns {string} The conjugated word (e.g., 'sitte')
 */

/**
 * Conjugates the base Inglisce word based on spaCy's fine-grained Penn Treebank tags.
 * Evaluates custom conjugations from the dictionary before falling back to standard suffix math.
 */

const applyMorphology = (brainEntry, word, tag) => {
    const c = brainEntry.conjugations || {};
    
    switch (tag) {
        case 'NNS': // Plural Noun
            const pluralSuffix = Array.isArray(c) && c.length > 0 ? c[0] : '-s';
            return resolveForm(pluralSuffix, word, false); 
        case 'VBZ': // 3rd Person Singular Verb (e.g., "he makes")
            return resolveForm(c.third_singular || '-s', word, false); 
        case 'VBD': // Past Tense Verb
            return resolveForm(c.past || '-d', word, false);
        case 'VBN': // Past Participle
            return resolveForm(c.participle || c.past || '-d', word, false);
        case 'VBG': // Gerund / Present Participle
            return resolveForm(c.gerund || '-ing', word, true); 
        default:
            return word; // Base form (No conjugation needed)
    }
};

/**
 * ============================================================================
 * PART 2: THE CORE ENGINE (PURE FUNCTION)
 * ============================================================================
 */

/**
 * Core Transcriber: Pure Reducer function implementing a Writer Monad pattern.
 * Instead of mutating a global string or array, this function passes an immutable
 * 'State Tuple' (the accumulator) down the chain. It returns both the final calculated
 * string AND a safe log of missing words, guaranteeing 100% mathematical purity.
 * @param {Array} astTokens - The JSON array generated by the Python spaCy server.
 * @param {object} brain - The parsed translationBrain.json dictionary.
 * @returns {object} { text: string, missingWords: Set }
 */
export const transcribeFromAST = (astTokens, brain) => {
    // Initial State Tuple: Empty text string, empty Set for missing words
    return astTokens.reduce((acc, token) => {
        
        // 1. Structural Bypass: Instantly pass through whitespace, punctuation marks,
        // unrecognized symbols (X), and Protected Entities (is_ent: true, like "Oedipus").
        if (token.pos === 'SPACE' || token.pos === 'PUNCT' || token.pos === 'X' || token.is_ent) {
            acc.text += token.text + token.whitespace;
            return acc;
        }

        const searchWord = token.lemma.toLowerCase();
        const rawWord = token.text.toLowerCase();
        
        // 2. Lookup Priority: Check the exact raw word FIRST to catch irregulars (e.g., "me", "are").
        // Only if it fails do we fall back to searching for the lemmatized root (e.g., "I", "be").
        const brainEntry = brain[rawWord] || brain[searchWord];

        // 3. Option Pattern: `brainEntry && ...` acts as a native JS Maybe Monad.
        // If brainEntry is undefined, this cleanly short-circuits to `null` without throwing an error.
        const baseReplacement = brainEntry && getReplacement(token.pos, brainEntry);
        
        if (baseReplacement) {
            // Conjugation Check: If we found the exact raw word in the dictionary (like "are"),
            // we assume it is already properly conjugated. We ONLY apply morphology if we 
            // had to fall back to the raw root/lemma.
            const finalWord = brain[rawWord] 
                ? baseReplacement 
                : applyMorphology(brainEntry, baseReplacement, token.tag);

            acc.text += matchCasing(token.text, finalWord) + token.whitespace;
            return acc;
        }

        // 4. Missing Word Handling (The Writer Log):
        // If translation fails, we append the untranslated word in brackets to the text,
        // and safely log the missing lemma to the monad's Set tracker to bubble up to the caller.
        acc.missingWords.add(searchWord);
        acc.text += `[${token.text}]` + token.whitespace;
        return acc;
        
    }, { text: '', missingWords: new Set() }); 
}

/**
 * ============================================================================
 * PART 3: THE CLI EXECUTION BOUNDARY (IMPURE SIDE-EFFECTS)
 * ============================================================================
 */

// Establish standard __filename and __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);

// Only execute the CLI script if this file is run directly (e.g., `node transcriber.js`)
if (process.argv[1] === __filename) {
    const inputPath = process.argv[2];
    const outputPath = process.argv[3];
    const __dirname = path.dirname(__filename);
    const BRAIN_PATH = path.resolve(__dirname, '../../toolkit/dist/translationBrain.json');

    if (!inputPath || !outputPath) {
        console.error("Usage: node scripts/transcriber.js <input_dir_or_file> <output_dir_or_file>");
        process.exit(1);
    }

    if (!fs.existsSync(BRAIN_PATH)) {
        console.error(`❌ Error: translationBrain.json is missing at ${BRAIN_PATH}`);
        process.exit(1);
    }

    // Load the dictionary into memory once
    const brain = JSON.parse(fs.readFileSync(BRAIN_PATH, 'utf8'));
    
    // This is the IMPURE global tracker. It lives here at the script's outer boundary
    // so the core engine can remain pure.
    const globalMissingWords = new Set();
    let filesProcessed = 0;

    /**
     * Recursively walks a directory tree, finds .json ASTs, translates them, 
     * and exports .txt files in an identical mirrored folder structure.
     */
    function crawlAndTranscribe(currentInputDir, currentOutputDir) {
        // Optimization: Ensure output folder exists once per directory, NOT once per file.
        if (!fs.existsSync(currentOutputDir)) {
            fs.mkdirSync(currentOutputDir, { recursive: true });
        }

        // withFileTypes allows us to cleanly check .isDirectory() without extra fs.stat() calls
        const entries = fs.readdirSync(currentInputDir, { withFileTypes: true });

        for (const entry of entries) {
            const fullInputPath = path.join(currentInputDir, entry.name);

            if (entry.isDirectory()) {
                const fullOutputPath = path.join(currentOutputDir, entry.name);
                crawlAndTranscribe(fullInputPath, fullOutputPath); // Recursive dive
            } else if (entry.name.endsWith('.json')) {
                // Change extension from .json AST back to readable .txt
                const outFileName = entry.name.replace(/\.json$/, '.txt');
                const fullOutputPath = path.join(currentOutputDir, outFileName);

                const astTokens = JSON.parse(fs.readFileSync(fullInputPath, 'utf8'));
                
                // Destructure the Monadic Response from our pure core engine
                const { text, missingWords } = transcribeFromAST(astTokens, brain);
                
                // Extract the missing words from the pure local Set and merge them into our impure global tracker
                missingWords.forEach(word => globalMissingWords.add(word));
                
                fs.writeFileSync(fullOutputPath, text, 'utf8');
                filesProcessed++;
            }
        }
    }

    // Check if the user passed a directory or a single file to the CLI
    const stat = fs.statSync(inputPath);

    if (stat.isDirectory()) {
        console.log(`📂 Crawling AST directory: ${inputPath}`);
        crawlAndTranscribe(inputPath, outputPath);
    } else {
        // Fallback: Process a single file
        console.log(`📝 Transcribing single AST: ${inputPath}`);
        const astTokens = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
        
        const { text, missingWords } = transcribeFromAST(astTokens, brain);
        missingWords.forEach(word => globalMissingWords.add(word));
        
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, text, 'utf8');
        filesProcessed++;
    }

    console.log(`\n✅ Transcription Complete! Processed ${filesProcessed} files.`);
    console.log(`➡️  Saved to: ${outputPath}`);

    // Print the global missing words sorted alphabetically for easy dictionary updates
    if (globalMissingWords.size > 0) {
        console.log(`\n⚠️  Master Missing Words Tracker (${globalMissingWords.size} unique untranslated words):`);
        console.log(Array.from(globalMissingWords).sort().join(', '));
    }
}